# Generated by Django 3.0.4 on 2022-04-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='movie',
        ),
    ]
