# Generated by Django 3.0.4 on 2022-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220418_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('occupant_first_name', models.CharField(max_length=255)),
                ('occupant_last_name', models.CharField(max_length=255)),
                ('occupant_email', models.EmailField(max_length=555)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='booked_seats',
            field=models.ManyToManyField(blank=True, to='base.Seat'),
        ),
    ]
